routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/charts', 'HomeController@charts')->name('charts');

   Route::get('/tables', 'HomeController@tables')->name('tables'); 
Route::get('/users/logout','Auth\LoginController@userLogout')->name('user.logout');


Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');    
    Route::get('/logout','Auth\AdminLoginController@logout')->name('admin.logout');    
    Route::post('/password/email','Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');   
    Route::get('/password/reset','Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::post('/password/reset','Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}','Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
    
    
    Route::get('/charts', 'AdminController@charts')->name('charts');
   Route::get('/tables', 'AdminController@tables')->name('tables'); 
     Route::resource('admins', 'admin\AdminAdminsController'); 
      Route::resource('users', 'admin\AdminUsersController'); 
       Route::resource('users', 'admin\AdminUsersController'); 
     Route::get('/exportar', 'AdminController@export')->name('exportar'); 
    
});

resources/views/admins/admins/create.blade.php
@extends('layoutsdashboard.base')

@section('css')

@endsection
@section('content')


<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="#">Dashboard</a>
    </li>
    <li class="breadcrumb-item"><a href="{{route('admins.index') }}">administradores</a></li>
    <li class="breadcrumb-item active">crear</li>
</ol>
<!-- Example DataTables Card-->
<div class="col-lg-8">
    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-user-cog"></i>Crear administradores del sistema</div>
        <div class="card-body">



            <form method="post" action="{{route('admins.store')}}">
                @csrf
                <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email" name="email" value="{{ old('email') }}">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                    @if ($errors->has('email')) 
                    <div class="alert alert-danger">
                        <strong>{{ $errors->first('email') }}</strong>
                    </div>
                    @endif

                </div>

                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Enter name" name="name" value="{{ old('name') }}">
                    @if ($errors->has('name')) 
                    <div class="alert alert-danger">
                        <strong>{{ $errors->first('name') }}</strong>
                    </div>
                    @endif
                </div>


                <div class="form-group">
                    <label for="exampleFormControlSelect1">Rol</label>
                    <select class="form-control" id="exampleFormControlSelect1" name="rol">
                        <option value="administrador">administrador</option>
                      
                    </select>
                </div>

                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password">
                    @if ($errors->has('password')) 
                    <div class="alert alert-danger">
                        <strong>{{ $errors->first('password') }}</strong>
                    </div>
                    @endif
                </div>

                <div class="form-group">
                    <label for="password_confirmation">Password</label>
                    <input type="password" class="form-control" id="password_confirmation" name="password_confirmation">
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>

        </div>

    </div>
</div>

@endsection

resources/views/admins/admins/edit.blade.php
@extends('layoutsdashboard.base')

@section('css')

@endsection
@section('content')


<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="#">Dashboard</a>
    </li>
    <li class="breadcrumb-item"><a href="{{route('admins.index') }}">administradores</a></li>
    <li class="breadcrumb-item active">crear</li>
</ol>
<!-- Example DataTables Card-->
<div class="col-lg-8">
    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-user-cog"></i>Crear administradores del sistema</div>
        <div class="card-body">



            <form method="post" action="{{route('admins.update',$admin->id)}}">
                {{ method_field('PUT') }}
                @csrf
                <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email" name="email" value="{{ $admin->email }}">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                    @if ($errors->has('email')) 
                    <div class="alert alert-danger">
                        <strong>{{ $errors->first('email') }}</strong>
                    </div>
                    @endif

                </div>

                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Enter email" name="name" value="{{$admin->name }}">
                    @if ($errors->has('name')) 
                    <div class="alert alert-danger">
                        <strong>{{ $errors->first('name') }}</strong>
                    </div>
                    @endif
                </div>


                <div class="form-group">
                    <label for="exampleFormControlSelect1">Rol</label>
                    <select class="form-control" id="exampleFormControlSelect1" name="rol">
                        <option value="administrador">administrador</option>
                      
                    </select>
                </div>

                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password">
                    @if ($errors->has('password')) 
                    <div class="alert alert-danger">
                        <strong>{{ $errors->first('password') }}</strong>
                    </div>
                    @endif
                </div>

                <div class="form-group">
                    <label for="password_confirmation">Password</label>
                    <input type="password" class="form-control" id="password_confirmation" name="password_confirmation">
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>

        </div>

    </div>
</div>

@endsection

resources/views/admins/admins/index.blade.php
@extends('layoutsdashboard.base')

@section('css')

@endsection
@section('content')


<ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">administradores</li>
      </ol>
      <!-- Example DataTables Card-->
      
       @if(Session::has('message_store'))
       <div class="alert alert-danger">
                        <strong>admin creado</strong>
         </div>
      @endif
      
       @if(Session::has('message_update'))
       <div class="alert alert-danger">
                        <strong>admin editado</strong>
         </div>
      @endif
       @if(Session::has('message_destroy'))
       <div class="alert alert-danger">
                        <strong>admin eliminado</strong>
         </div>
      @endif
      
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-table"></i> Data Table Example</div>
        <div class="card-body">
         
          <a href="{{route('admins.create')}}" class="btn btn-primary">Crear</a>
          
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Position</th>
                  <th>email</th>                  
                   <th>acciones</th>    
                
                </tr>
              </thead>
         
              <tbody>
               @foreach($admins as $admin)
                <tr>
                  <td>{{$admin->name}}</td>
                  <td>{{$admin->rol}}</td>
                  <td>{{$admin->email}}</td>
                 <td>
                     <a href="{{route('admins.edit',$admin->id)}}"><i class="fas fa-user-edit"></i></a>
                     <a href="#" onclick="showConfirmDeleteModal('{{route('admins.destroy',$admin->id)}}','{{$admin->name}}')"><i class="fas fa-trash-alt"></i></a>
                 </td>
                
                 
                </tr>
               @endforeach
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
      </div>



@endsection


@section('js')
<script src="{{asset('adminstyle/js/jquery.dataTables.js')}}"></script>
<script src="{{asset('adminstyle/js/dataTables.bootstrap4.js')}}"></script>
<script src="{{asset('adminstyle/js/sb-admin-datatables.js')}}"></script>
<script>

function showConfirmDeleteModal (url,name){
    $('#deleteForm').prop('action', url);
    $('#deleteName').text(name);
     $('#deleteModal').modal();
}
</script>
@endsection