routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/charts', 'HomeController@charts')->name('charts');

   Route::get('/tables', 'HomeController@tables')->name('tables'); 
Route::get('/users/logout','Auth\LoginController@userLogout')->name('user.logout');


Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');    
    Route::get('/logout','Auth\AdminLoginController@logout')->name('admin.logout');    
    Route::post('/password/email','Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');   
    Route::get('/password/reset','Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::post('/password/reset','Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}','Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
    
    
    Route::get('/charts', 'AdminController@charts')->name('charts');
   Route::get('/tables', 'AdminController@tables')->name('tables'); 
     Route::resource('admins', 'admin\AdminAdminsController'); 
      Route::resource('users', 'admin\AdminUsersController'); 
       Route::resource('users', 'admin\AdminUsersController'); 
     Route::get('/exportar', 'AdminController@export')->name('exportar'); 
    
});

app/User.php
<?php

namespace App;

use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
     use HasApiTokens, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

//use App\Http\Controllers\Controller;
use App\User;
use Hash;
use Illuminate\Http\Request;
use App\Http\Controllers\ApiController;

class UserController extends ApiController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $usuarios=User::all();
        return $this->showAll($usuarios);
        //return response()->json(['data'=>$usuarios],200);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $campos['password']= Hash::make($request->password);
        $reglas=['name'=>'required','last_name'=>'required','email'=>'required|email|unique:users','password'=>'required|confirmed','address'=>'required','latitud'=>'required','longitud'=>'required','type'=>'required','neighborhood'=>'required','city_id'=>'required'];

        $this->validate($request, $reglas);

        $usuario=[
         'name'=>$request->name,
         'last_name'=>$request->last_name,
         'email'=>$request->email,
         'password'=>Hash::make($request->password),
         'phone'=>$request->phone,
         'rol_id'=>$request->rol_id
        ];

        $usuario= User::create($usuario);
        $usuario->id;
        $punto=$request->latitud.' '.$request->longitud;
        //   $sector_id=$this->buscarSector($punto,$request->city_id);

        return $this->showOne($usuario, 201);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return $this->showOne($user, 200);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $usuario=User::findOrFail($id);
        $usuario->delete();
        return $this->showOne($usuario, 201);
    }

    public function buscarSector($punto, $city_id)
    {
        //  $punto=$this->puntoCoordenadas($punto);

        $sectores=Sector::where('city_id', $city_id)->get();

        foreach ($sectores as $sector) {
            $poligono=explode(",", $sector->polygon);
            $ubicacion=$this->pointInPolygon($punto, $poligono);
        }
        dd($ubicacion);
        return $this->showAll($sectores);


        dd($sectores);
        dd($punto);
    }




    public function pointInPolygon($point, $polygon, $pointOnVertex = true)
    {
        //$this->pointOnVertex = $pointOnVertex;

        // Transformar la cadena de coordenadas en matrices con valores "x" e "y"
        //   $point = $this->pointStringToCoordinates($point);
        $vertices = array();

        foreach ($polygon as $vertex) {
            $vertices[] = $this->pointStringToCoordinates($vertex);
        }

        // Checar si el punto se encuentra exactamente en un vértice
        if ($pointOnVertex == true and $this->pointOnVertex($point, $vertices) == true) {
            return "vertex";
            dd('vertes');
        }

        // Checar si el punto está adentro del poligono o en el borde
        $intersections = 0;
        $vertices_count = count($vertices);
        dd($vertices);
        for ($i=1; $i < $vertices_count; $i++) {
            $vertex1 = $vertices[$i-1];
            $vertex2 = $vertices[$i];

            if ($vertex1['y'] == $vertex2['y'] and $vertex1['y'] == $point['y'] and $point['x'] > min($vertex1['x'], $vertex2['x']) and $point['x'] < max($vertex1['x'], $vertex2['x'])) {
                // Checar si el punto está en un segmento horizontal
                return "boundary";
            }
            if ($point['y'] > min($vertex1['y'], $vertex2['y']) and $point['y'] <= max($vertex1['y'], $vertex2['y']) and $point['x'] <= max($vertex1['x'], $vertex2['x']) and $vertex1['y'] != $vertex2['y']) {
                $xinters = ($point['y'] - $vertex1['y']) * ($vertex2['x'] - $vertex1['x']) / ($vertex2['y'] - $vertex1['y']) + $vertex1['x'];
                if ($xinters == $point['x']) { // Checar si el punto está en un segmento (otro que horizontal)
                    return "boundary";
                }
                if ($vertex1['x'] == $vertex2['x'] || $point['x'] <= $xinters) {
                    $intersections++;
                }
            }
        }
        // Si el número de intersecciones es impar, el punto está dentro del poligono.
        if ($intersections % 2 != 0) {
            return "inside";
        } else {
            return "outside";
        }
    }

    public function pointOnVertex($point, $vertices)
    {
        foreach ($vertices as $vertex) {
            if ($point == $vertex) {
                return true;
            }
        }
    }

    public function pointStringToCoordinates($pointString)
    {
        $coordinates = explode(" ", $pointString);
        return array("x" => $coordinates[0], "y" => $coordinates[1]);
    }
}

resources/views/admins/users/create.blade.php
@extends('layoutsdashboard.base')

@section('css')

@endsection
@section('content')


<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="#">Dashboard</a>
    </li>
    <li class="breadcrumb-item"><a href="{{route('users.index') }}">usuarios</a></li>
    <li class="breadcrumb-item active">crear</li>
</ol>
<!-- Example DataTables Card-->
<div class="col-lg-8">
    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-user-cog"></i>Crear usuarios</div>
        <div class="card-body">



            <form method="post" action="{{route('users.store')}}">
                @csrf
                <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email" name="email" value="{{ old('email') }}">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                    @if ($errors->has('email')) 
                    <div class="alert alert-danger">
                        <strong>{{ $errors->first('email') }}</strong>
                    </div>
                    @endif

                </div>

                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Enter email" name="name" value="{{ old('name') }}">
                    @if ($errors->has('name')) 
                    <div class="alert alert-danger">
                        <strong>{{ $errors->first('name') }}</strong>
                    </div>
                    @endif
                </div>


                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password">
                    @if ($errors->has('password')) 
                    <div class="alert alert-danger">
                        <strong>{{ $errors->first('password') }}</strong>
                    </div>
                    @endif
                </div>

                <div class="form-group">
                    <label for="password_confirmation">Password</label>
                    <input type="password" class="form-control" id="password_confirmation" name="password_confirmation">
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>

        </div>

    </div>
</div>

@endsection

resources/views/admins/users/edit.blade.php
@extends('layoutsdashboard.base')

@section('css')

@endsection
@section('content')


<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="#">Dashboard</a>
    </li>
    <li class="breadcrumb-item"><a href="{{route('users.index') }}">administradores</a></li>
    <li class="breadcrumb-item active">crear</li>
</ol>
<!-- Example DataTables Card-->
<div class="col-lg-8">
    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-user-cog"></i>Crear administradores del sistema</div>
        <div class="card-body">



            <form method="post" action="{{route('users.update',$user->id)}}">
                {{ method_field('PUT') }}
                @csrf
                <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email" name="email" value="{{ $user->email }}">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                    @if ($errors->has('email')) 
                    <div class="alert alert-danger">
                        <strong>{{ $errors->first('email') }}</strong>
                    </div>
                    @endif

                </div>

                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Enter email" name="name" value="{{$user->name }}">
                    @if ($errors->has('name')) 
                    <div class="alert alert-danger">
                        <strong>{{ $errors->first('name') }}</strong>
                    </div>
                    @endif
                </div>



                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password">
                    @if ($errors->has('password')) 
                    <div class="alert alert-danger">
                        <strong>{{ $errors->first('password') }}</strong>
                    </div>
                    @endif
                </div>

                <div class="form-group">
                    <label for="password_confirmation">Password</label>
                    <input type="password" class="form-control" id="password_confirmation" name="password_confirmation">
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>

        </div>

    </div>
</div>

@endsection

resources/views/admins/users/index.blade.php
@extends('layoutsdashboard.base')

@section('css')

@endsection
@section('content')


<ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Usuarios</li>
      </ol>
      <!-- Example DataTables Card-->
      
       @if(Session::has('message_store'))
       <div class="alert alert-danger">
                        <strong>usuario creado</strong>
         </div>
      @endif
      
       @if(Session::has('message_update'))
       <div class="alert alert-danger">
                        <strong>usuario editado</strong>
         </div>
      @endif
       @if(Session::has('message_destroy'))
       <div class="alert alert-danger">
                        <strong>usuario eliminado</strong>
         </div>
      @endif
      
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-table"></i> Data Table Example</div>
        <div class="card-body">
         
          <a href="{{route('users.create')}}" class="btn btn-primary">Crear</a>
            <a href="{{route('exportar')}}" class="btn btn-primary">Exportar</a>
          
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Name</th>              
                  <th>email</th>                  
                   <th>acciones</th>    
                
                </tr>
              </thead>
         
              <tbody>
               @foreach($users as $user)
                <tr>
                  <td>{{$user->name}}</td>                
                  <td>{{$user->email}}</td>
                 <td>
                     <a href="{{route('users.edit',$user->id)}}"><i class="fas fa-user-edit"></i></a>
                     <a href="#" onclick="showConfirmDeleteModal('{{route('users.destroy',$user->id)}}','{{$user->name}}')"><i class="fas fa-trash-alt"></i></a>
                 </td>
                
                 
                </tr>
               @endforeach
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
      </div>



@endsection


@section('js')
<script src="{{asset('adminstyle/js/jquery.dataTables.js')}}"></script>
<script src="{{asset('adminstyle/js/dataTables.bootstrap4.js')}}"></script>
<script src="{{asset('adminstyle/js/sb-admin-datatables.js')}}"></script>
<script>

function showConfirmDeleteModal (url,name){
    $('#deleteForm').prop('action', url);
    $('#deleteName').text(name);
     $('#deleteModal').modal();
}
</script>
@endsection